preprocessing:
  build_graphs:
    used_method: orthrus
    use_all_files: True
    time_window_size: 15.0
    use_hashed_label: True
    node_label_features:
      subject: type, path, cmd_line
      file: type, path
      netflow: type, remote_ip, remote_port

featurization:
  embed_nodes:
    emb_dim: 128
    used_method: feature_word2vec
    use_seed: True
    feature_word2vec:
      show_epoch_loss: True
      window_size: 5
      min_count: 1
      use_skip_gram: True
      num_workers: 6
      epochs: 50
      compute_loss: True
      negative: 5
      use_node_types: False
      use_cmd: True
      use_port: False
      decline_rate: 30
  embed_edges:
    to_remove: True

detection:
  gnn_training:
    used_method: orthrus
    use_seed: True
    num_epochs: 6
    lr: 0.00001
    weight_decay: 0.00001
    node_hid_dim: 128
    node_out_dim: 64
    encoder:
      use_node_type_in_node_feats: True
      neighbor_sampling: []
      edge_features: edge_type
      use_node_feats_in_gnn: True
      neighbor_size: 20
      temporal_dim: 100
      batch_size: 1024
      graph_attention:
        dropout: 0.5
        activation: relu
        num_heads: 8
    decoder:
      used_methods: predict_edge_type
      predict_edge_type:
        used_method: custom
        custom:
          dropout: 0.0
          num_layers: 2
          activation: relu

  gnn_testing:
    threshold_method: str
  evaluation:
    viz_malicious_nodes: False
    ground_truth_version: darpa
    used_method: node_evaluation
    node_evaluation:
      threshold_method: max_val_loss
      use_dst_node_loss: True
      use_kmeans: True
      kmeans_top_K: 20

triage :
  tracing:
    used_method: depimpact
    depimpact:
      used_method: component
      score_method: degree
      workers: 8
      visualize: False
